#!/usr/bin/env bash

output=$(sudo \
    ln -s \
        $(python2 -c "import os; print os.path.abspath('agentd.py')" 2>&1) \
        /usr/local/bin/agentd 2>&1)

if [ -z "$output" ]
then
    echo "Success!"
else
    file_exist_flag=$(grep "File exists" <<<"$output")
    if [ -z "$file_exist_flag" ]
    then
        echo -e "something goes wrong\ndetails:\n"
        echo "$output"
    else
        echo "Already setted up."
    fi
fi
